shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - 'semver@6.3.1'

allowBuilds:
  '@parcel/watcher': false
  '@prisma/client': false
  '@prisma/engines': false
  esbuild: false
  prisma: false
  sharp: true
  unrs-resolver: false
  vue-demi: false
  workerd: false
