import type { LetterAssetOption, LetterRecipient } from './types'

export const LETTER_RECIPIENTS: { id: LetterRecipient, label: string, description: string }[] = [
  { id: 'maloi', label: 'Maloi', description: 'Send a letter to Maloi' },
  { id: 'jhoanna', label: 'Jhoanna', description: 'Send a letter to Jhoanna' },
  { id: 'bini', label: 'BINI', description: 'Send a letter to BINI' },
]

/** Public URL under /public/images/letters */
export function letterImageUrl(
  kind: 'backgrounds' | 'seals' | 'stickers',
  file: number | string,
) {
  return `/images/letters/${kind}/${file}.png`
}

export const LETTER_BACKGROUNDS: LetterAssetOption[] = [
  { id: 'bg-1', label: 'Blue gingham', preview: letterImageUrl('backgrounds', 1) },
  { id: 'bg-2', label: 'Sky dots', preview: letterImageUrl('backgrounds', 2) },
  { id: 'bg-3', label: 'Blush stripes', preview: letterImageUrl('backgrounds', 3) },
  { id: 'bg-4', label: 'Sky stripes', preview: letterImageUrl('backgrounds', 4) },
  { id: 'bg-5', label: 'Mint wash', preview: letterImageUrl('backgrounds', 5) },
  { id: 'bg-6', label: 'Sea rings', preview: letterImageUrl('backgrounds', 6) },
  { id: 'bg-7', label: 'Aqua glow', preview: letterImageUrl('backgrounds', 7) },
  { id: 'bg-8', label: 'Teal check', preview: letterImageUrl('backgrounds', 8) },
  { id: 'bg-9', label: 'Yellow gingham', preview: letterImageUrl('backgrounds', 9) },
  { id: 'bg-10', label: 'Butter wash', preview: letterImageUrl('backgrounds', 10) },
  { id: 'bg-11', label: 'Lemon wash', preview: letterImageUrl('backgrounds', 11) },
  { id: 'bg-12', label: 'Yellow stripes', preview: letterImageUrl('backgrounds', 12) },
  { id: 'bg-13', label: 'Teal diagonal check', preview: letterImageUrl('backgrounds', 13) },
  { id: 'bg-14', label: 'Turquoise glow', preview: letterImageUrl('backgrounds', 14) },
  { id: 'bg-15', label: 'Teal mist', preview: letterImageUrl('backgrounds', 15) },
  { id: 'bg-16', label: 'Ivory paper', preview: letterImageUrl('backgrounds', 16) },
  { id: 'bg-17', label: 'Graph paper', preview: letterImageUrl('backgrounds', 17) },
  { id: 'bg-18', label: 'Icy crumple', preview: letterImageUrl('backgrounds', 18) },
  { id: 'bg-19', label: 'Crumpled parchment', preview: letterImageUrl('backgrounds', 19) },
  { id: 'bg-20', label: 'Sky crumple', preview: letterImageUrl('backgrounds', 20) },
  { id: 'bg-21', label: 'Gold fleck cream', preview: letterImageUrl('backgrounds', 21) },
  { id: 'bg-22', label: 'Warm parchment', preview: letterImageUrl('backgrounds', 22) },
]

export const LETTER_FONTS: LetterAssetOption[] = [
  { id: 'hand', label: 'Handwriting' },
  { id: 'script', label: 'Script' },
  { id: 'type', label: 'Typewriter' },
  { id: 'sans', label: 'Clean sans' },
  { id: 'casual', label: 'Casual pen' },
  { id: 'seine', label: 'Seine' },
  { id: 'crayon', label: 'Crayon' },
  { id: 'bloom', label: 'Bloom' },
  { id: 'handflair', label: 'Handflair' },
  { id: 'lazy', label: 'Lazy dog' },
  { id: 'jardin', label: 'Jardin' },
  { id: 'privilege', label: 'Privilege' },
  { id: 'salmon', label: 'Salmon bake' },
  { id: 'summer', label: 'Summer' },
  { id: 'nanti', label: 'Tentang nanti' },
]

/** Color-only envelopes (shared paper grain in CSS) */
export const LETTER_ENVELOPES: LetterAssetOption[] = [
  { id: 'envelope-white', label: 'White' },
  { id: 'envelope-cream', label: 'Cream' },
  { id: 'envelope-blush', label: 'Blush' },
  { id: 'envelope-sky', label: 'Sky' },
  { id: 'envelope-lilac', label: 'Lilac' },
  { id: 'envelope-mint', label: 'Mint' },
  { id: 'envelope-kraft', label: 'Kraft' },
  { id: 'envelope-slate', label: 'Slate' },
]

export const LETTER_SEALS: LetterAssetOption[] = [
  { id: 'seal-1', label: 'Ice blank', preview: letterImageUrl('seals', 1) },
  { id: 'seal-2', label: 'Pink bow', preview: letterImageUrl('seals', 2) },
  { id: 'seal-3', label: 'Gold plume', preview: letterImageUrl('seals', 3) },
  { id: 'seal-4', label: 'Forest bloom', preview: letterImageUrl('seals', 4) },
  { id: 'seal-5', label: 'Sunburst', preview: letterImageUrl('seals', 5) },
  { id: 'seal-6', label: 'Blue sprig', preview: letterImageUrl('seals', 6) },
  { id: 'seal-7', label: 'Gold heart', preview: letterImageUrl('seals', 7) },
  { id: 'seal-8', label: 'Royal blue', preview: letterImageUrl('seals', 8) },
  { id: 'seal-9', label: 'Red heart', preview: letterImageUrl('seals', 9) },
  { id: 'seal-10', label: 'Lilac blank', preview: letterImageUrl('seals', 10) },
  { id: 'seal-11', label: 'Jade blank', preview: letterImageUrl('seals', 11) },
  { id: 'seal-12', label: 'Blue botanical', preview: letterImageUrl('seals', 12) },
  { id: 'seal-13', label: 'Rose stamp', preview: letterImageUrl('seals', 13) },
  { id: 'seal-14', label: 'Poppy stamp', preview: letterImageUrl('seals', 14) },
  { id: 'seal-15', label: 'Ruby heart', preview: letterImageUrl('seals', 15) },
  { id: 'seal-16', label: 'Gold star seal', preview: letterImageUrl('seals', 16) },
  { id: 'seal-17', label: 'Emerald tulips', preview: letterImageUrl('seals', 17) },
  { id: 'seal-18', label: 'Blush heart', preview: letterImageUrl('seals', 18) },
  { id: 'seal-19', label: 'Pearl treble clef', preview: letterImageUrl('seals', 19) },
  { id: 'seal-20', label: 'Navy lily', preview: letterImageUrl('seals', 20) },
  { id: 'seal-21', label: 'Pink bow', preview: letterImageUrl('seals', 21) },
  { id: 'seal-22', label: 'Green clover', preview: letterImageUrl('seals', 22) },
]

export const LETTER_STICKERS: LetterAssetOption[] = [
  { id: 'sticker-1', label: 'Peony stamp', preview: letterImageUrl('stickers', 1) },
  { id: 'sticker-2', label: 'Vintage postage', preview: letterImageUrl('stickers', 2) },
  { id: 'sticker-3', label: 'Yellow bloom stamp', preview: letterImageUrl('stickers', 3) },
  { id: 'sticker-4', label: 'Sunflower stamp', preview: letterImageUrl('stickers', 4) },
  { id: 'sticker-5', label: 'Blue flower stamp', preview: letterImageUrl('stickers', 5) },
  { id: 'sticker-6', label: 'Daisy stamp', preview: letterImageUrl('stickers', 6) },
  { id: 'sticker-7', label: 'Meadow stamp', preview: letterImageUrl('stickers', 7) },
  { id: 'sticker-8', label: 'Gladiolus stamp', preview: letterImageUrl('stickers', 8) },
  { id: 'sticker-9', label: 'Blossom stamp', preview: letterImageUrl('stickers', 9) },
  { id: 'sticker-10', label: 'Pink bouquet stamp', preview: letterImageUrl('stickers', 10) },
  { id: 'sticker-11', label: 'Sunny daisy stamp', preview: letterImageUrl('stickers', 11) },
  { id: 'sticker-12', label: 'Postmark', preview: letterImageUrl('stickers', 12) },
  { id: 'sticker-13', label: 'Magic wand', preview: letterImageUrl('stickers', 13) },
  { id: 'sticker-14', label: 'Magic wand sparkle', preview: letterImageUrl('stickers', 14) },
  { id: 'sticker-15', label: 'Cosmos bloom', preview: letterImageUrl('stickers', 15) },
  { id: 'sticker-16', label: 'Blue florals', preview: letterImageUrl('stickers', 16) },
  { id: 'sticker-17', label: 'Teal hibiscus', preview: letterImageUrl('stickers', 17) },
  { id: 'sticker-18', label: 'Sunset hibiscus', preview: letterImageUrl('stickers', 18) },
  { id: 'sticker-19', label: 'Daisy cluster', preview: letterImageUrl('stickers', 19) },
  { id: 'sticker-20', label: 'Daisy bloom', preview: letterImageUrl('stickers', 20) },
  { id: 'sticker-21', label: 'Lily blossom', preview: letterImageUrl('stickers', 21) },
  { id: 'sticker-22', label: 'Lightstick tilt', preview: letterImageUrl('stickers', 22) },
  { id: 'sticker-23', label: 'Lightstick', preview: letterImageUrl('stickers', 23) },
  { id: 'sticker-24', label: 'Pink cosmos', preview: letterImageUrl('stickers', 24) },
  { id: 'sticker-25', label: 'Blue blooms', preview: letterImageUrl('stickers', 25) },
  { id: 'sticker-26', label: 'Aqua hibiscus', preview: letterImageUrl('stickers', 26) },
  { id: 'sticker-27', label: 'Yellow hibiscus', preview: letterImageUrl('stickers', 27) },
  { id: 'sticker-28', label: 'Daisies', preview: letterImageUrl('stickers', 28) },
  { id: 'sticker-29', label: 'Daisy', preview: letterImageUrl('stickers', 29) },
  { id: 'sticker-30', label: 'White lily', preview: letterImageUrl('stickers', 30) },
  { id: 'sticker-31', label: 'Smiley stamp', preview: letterImageUrl('stickers', 31) },
  { id: 'sticker-32', label: 'Yellow stars', preview: letterImageUrl('stickers', 32) },
  { id: 'sticker-33', label: 'Pink heart', preview: letterImageUrl('stickers', 33) },
  { id: 'sticker-34', label: 'Believe in yourself', preview: letterImageUrl('stickers', 34) },
  { id: 'sticker-35', label: 'Never stop working', preview: letterImageUrl('stickers', 35) },
  { id: 'sticker-36', label: 'Never give up', preview: letterImageUrl('stickers', 36) },
  { id: 'sticker-37', label: 'Butterfly', preview: letterImageUrl('stickers', 37) },
  { id: 'sticker-38', label: 'Take it easy', preview: letterImageUrl('stickers', 38) },
  { id: 'sticker-39', label: 'Cheers love', preview: letterImageUrl('stickers', 39) },
  { id: 'sticker-40', label: 'Cherries', preview: letterImageUrl('stickers', 40) },
  { id: 'sticker-41', label: 'Navy hearts', preview: letterImageUrl('stickers', 41) },
  { id: 'sticker-42', label: 'You are enough', preview: letterImageUrl('stickers', 42) },
  { id: 'sticker-43', label: 'One of a kind', preview: letterImageUrl('stickers', 43) },
  { id: 'sticker-44', label: 'All the good things', preview: letterImageUrl('stickers', 44) },
  { id: 'sticker-45', label: 'Take care of your mind', preview: letterImageUrl('stickers', 45) },
  { id: 'sticker-46', label: 'Blue hearts', preview: letterImageUrl('stickers', 46) },
  { id: 'sticker-47', label: 'Sunny face', preview: letterImageUrl('stickers', 47) },
  { id: 'sticker-48', label: 'Corgi', preview: letterImageUrl('stickers', 48) },
  { id: 'sticker-49', label: 'Cat face', preview: letterImageUrl('stickers', 49) },
  { id: 'sticker-50', label: 'Halftone corgi', preview: letterImageUrl('stickers', 50) },
  { id: 'sticker-51', label: 'Fluffy cat', preview: letterImageUrl('stickers', 51) },
  { id: 'sticker-52', label: 'Keep going', preview: letterImageUrl('stickers', 52) },
  { id: 'sticker-53', label: 'Protect your peace', preview: letterImageUrl('stickers', 53) },
  { id: 'sticker-54', label: "Bad days don't stay", preview: letterImageUrl('stickers', 54) },
  { id: 'sticker-55', label: 'Make yourself a priority', preview: letterImageUrl('stickers', 55) },
  { id: 'sticker-56', label: 'Dream big', preview: letterImageUrl('stickers', 56) },
  { id: 'sticker-57', label: 'Keep moving forward', preview: letterImageUrl('stickers', 57) },
  { id: 'sticker-58', label: 'Rooting for you', preview: letterImageUrl('stickers', 58) },
  { id: 'sticker-59', label: 'Yellow clover', preview: letterImageUrl('stickers', 59) },
  { id: 'sticker-60', label: 'Blue flower', preview: letterImageUrl('stickers', 60) },
  { id: 'sticker-61', label: 'You are enough heart', preview: letterImageUrl('stickers', 61) },
  { id: 'sticker-62', label: 'Green clover', preview: letterImageUrl('stickers', 62) },
]

export const LETTER_DEFAULTS = {
  background: 'bg-1' as const,
  font: LETTER_FONTS[0]!.id,
  envelope: LETTER_ENVELOPES[0]!.id,
  seal: 'seal-7' as const,
  /** YouTube watch URL, e.g. https://www.youtube.com/watch?v=… */
  music: undefined as string | undefined,
  stickers: [] as { id: string, x: number, y: number, rotation: number, scale: number }[],
}

export const LETTER_LIMITS = {
  bodyMax: 1500,
  postcardBodyMax: 300,
  senderNameMax: 50,
  stickersMax: 20,
  musicUrlMax: 500,
} as const

/** Tuple helpers so zod.enum accepts option id lists */
export const LETTER_OPTION_IDS = {
  backgrounds: [
    'bg-1',
    'bg-2',
    'bg-3',
    'bg-4',
    'bg-5',
    'bg-6',
    'bg-7',
    'bg-8',
    'bg-9',
    'bg-10',
    'bg-11',
    'bg-12',
    'bg-13',
    'bg-14',
    'bg-15',
    'bg-16',
    'bg-17',
    'bg-18',
    'bg-19',
    'bg-20',
    'bg-21',
    'bg-22',
  ] as const,
  fonts: [
    'hand',
    'script',
    'type',
    'sans',
    'casual',
    'seine',
    'crayon',
    'bloom',
    'handflair',
    'lazy',
    'jardin',
    'privilege',
    'salmon',
    'summer',
    'nanti',
  ] as const,

  envelopes: [
    'envelope-white',
    'envelope-cream',
    'envelope-blush',
    'envelope-sky',
    'envelope-lilac',
    'envelope-mint',
    'envelope-kraft',
    'envelope-slate',
  ] as const,
  seals: [
    'seal-1',
    'seal-2',
    'seal-3',
    'seal-4',
    'seal-5',
    'seal-6',
    'seal-7',
    'seal-8',
    'seal-9',
    'seal-10',
    'seal-11',
    'seal-12',
    'seal-13',
    'seal-14',
    'seal-15',
    'seal-16',
    'seal-17',
    'seal-18',
    'seal-19',
    'seal-20',
    'seal-21',
    'seal-22',
  ] as const,
  stickers: [
    'sticker-1',
    'sticker-2',
    'sticker-3',
    'sticker-4',
    'sticker-5',
    'sticker-6',
    'sticker-7',
    'sticker-8',
    'sticker-9',
    'sticker-10',
    'sticker-11',
    'sticker-12',
    'sticker-13',
    'sticker-14',
    'sticker-15',
    'sticker-16',
    'sticker-17',
    'sticker-18',
    'sticker-19',
    'sticker-20',
    'sticker-21',
    'sticker-22',
    'sticker-23',
    'sticker-24',
    'sticker-25',
    'sticker-26',
    'sticker-27',
    'sticker-28',
    'sticker-29',
    'sticker-30',
    'sticker-31',
    'sticker-32',
    'sticker-33',
    'sticker-34',
    'sticker-35',
    'sticker-36',
    'sticker-37',
    'sticker-38',
    'sticker-39',
    'sticker-40',
    'sticker-41',
    'sticker-42',
    'sticker-43',
    'sticker-44',
    'sticker-45',
    'sticker-46',
    'sticker-47',
    'sticker-48',
    'sticker-49',
    'sticker-50',
    'sticker-51',
    'sticker-52',
    'sticker-53',
    'sticker-54',
    'sticker-55',
    'sticker-56',
    'sticker-57',
    'sticker-58',
    'sticker-59',
    'sticker-60',
    'sticker-61',
    'sticker-62',
  ] as const,
}
